from pathlib import Path

from dotenv import load_dotenv
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser, StrOutputParser
from langchain_core.runnables import RunnableLambda
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

# Load environment variables from the .env file
# This includes OpenAI and LangSmith settings
load_dotenv()

# Example product reviews
reviews = [
    "I really liked the camera. It is the first time I take photos with a camera. "
    "I took some pictures, not of people yet, but of objects. I will post them for you to see.",

    "Perfect! High quality, it comes with everything described and I got a wonderful gift. "
    "I checked everything, origin, etc. Everything is ok. You will not regret it.",

    "One of the best cost-benefit Canon cameras for beginners. Good connectivity. "
    "Easy to learn how to use. It is worth it for those who do not want to spend too much "
    "but want a semi-professional camera.",

    "The camera presentation is very good, but I need a smaller and more compact camera."
]


class ReviewEvaluation(BaseModel):
    """
    Evaluate a product review written by a customer.

    The goal is to understand whether the review is positive,
    whether the product is worth buying, and what the main positive
    and negative points are.
    """

    positive_review: bool = Field(
        description="Is this review positive or negative?"
    )

    worth_buying: bool = Field(
        description="Does this review generally say that the product is worth buying?"
    )

    positive_points: list[str] = Field(
        description=(
            "Main positive points mentioned in the review. "
            "Each point must have a maximum of 3 words."
        )
    )

    negative_points: list[str] = Field(
        description=(
            "Main negative points mentioned in the review. "
            "Each point must have a maximum of 3 words."
        )
    )


class ReviewEvaluationList(BaseModel):
    """
    Store the structured evaluation results for multiple reviews.
    """

    evaluations: list[ReviewEvaluation] = Field(
        description="List containing the evaluation of each review."
    )


# Create a JSON parser based on the Pydantic model
review_parser = JsonOutputParser(
    name="user_review_evaluation",
    pydantic_object=ReviewEvaluationList
)

# Get format instructions generated by the parser
format_instructions = review_parser.get_format_instructions()

# Template that provides the reviews context
context_template = PromptTemplate.from_template(
    "You are evaluating multiple customer reviews about a product. "
    "Extract the requested information from each review in this list: {reviews}. "
)

# Template that defines the response language
language_template = PromptTemplate.from_template(
    "Always answer in {language}. ",
    partial_variables={
        "language": "English"
    }
)

# Template that defines the expected output format
format_template = PromptTemplate.from_template(
    "Response format: {format_instructions}. ",
    partial_variables={
        "format_instructions": format_instructions
    }
)

# Combine all prompt templates into one final template
review_template = (
    context_template
    + language_template
    + format_template
)

# Create a LangChain chat model connected to OpenAI
model = ChatOpenAI()

# First chain:
# reviews -> structured review evaluations
review_analysis_chain = review_template | model | review_parser

# Template for the second chain:
# structured evaluations -> final text analysis
summary_template = PromptTemplate.from_template(
    """
    Analyze the following list of product review evaluations and answer:

    1. How many reviews are positive and how many are negative?
       Also calculate the percentage of positive reviews.
    2. What percentage of reviews says the product is worth buying?
    3. What is the most frequent positive point and the most frequent negative point?

    Review evaluations: {evaluations}
    """
)

# Parser that returns only the final text response
text_parser = StrOutputParser()

# Second chain:
# structured review evaluations -> text summary
summary_chain = summary_template | model | text_parser


def save_reviews_to_file(review_data: dict) -> dict:
    """
    Save the structured review evaluations to a local text file.

    The function returns the same data it received so the next chain
    can continue using it.
    """

    output_folder = Path(__file__).parent / "generated"
    output_folder.mkdir(exist_ok=True)

    output_file_path = output_folder / "reviews.txt"

    with open(output_file_path, "w", encoding="utf-8") as output_file:
        for evaluation in review_data["evaluations"]:
            output_file.write(f"{evaluation}\n")

    return review_data


# Convert a regular Python function into a LangChain runnable step
save_reviews_runnable = RunnableLambda(save_reviews_to_file)

# Global chain:
# reviews -> structured evaluations -> save file -> final summary
global_chain = review_analysis_chain | save_reviews_runnable | summary_chain

# Run the full chain
analysis_response = global_chain.invoke(
    {
        "reviews": reviews
    }
)

# Display the final analysis
print(analysis_response)