from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Create an OpenAI client
client = OpenAI()

# Send a message to the model and generate a response
response = client.chat.completions.create(
    model="gpt-5.5",
    messages=[
        {
            "role": "user",
            "content": "Why is Python a good programming language?"
        }
    ]
)

# Access the first message generated by the model
response_message = response.choices[0].message

# Extract the content and role from the response message
message_content = response_message.content
message_role = response_message.role

# Display the response information
print("Role:", message_role)
print("Content:", message_content)