from dotenv import load_dotenv
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

# Load environment variables from the .env file
load_dotenv()

# Example product reviews
reviews = [
    "I really liked the camera. It is the first time I take photos with a camera. "
    "I took some pictures, not of people yet, but of objects. I will post them for you to see.",

    "Perfect! High quality, it comes with everything described and I got a wonderful gift. "
    "I checked everything, origin, etc. Everything is ok. You will not regret it.",

    "One of the best cost-benefit Canon cameras for beginners. Good connectivity. "
    "Easy to learn how to use. It is worth it for those who do not want to spend too much "
    "but want a semi-professional camera.",

    "The camera presentation is very good, but I need a smaller and more compact camera."
]


class ReviewEvaluation(BaseModel):
    """
    Evaluate a product review written by a customer.

    The goal is to understand whether the review is positive,
    whether the product is worth buying, and what the main positive
    and negative points are.
    """

    positive_review: bool = Field(
        description="Is this review positive or negative?"
    )

    worth_buying: bool = Field(
        description="Does this review generally say that the product is worth buying?"
    )

    positive_points: list[str] = Field(
        description=(
            "Main positive points mentioned in the review. "
            "Each point must have a maximum of 3 words."
        )
    )

    negative_points: list[str] = Field(
        description=(
            "Main negative points mentioned in the review. "
            "Each point must have a maximum of 3 words."
        )
    )


# Create a JSON parser based on the Pydantic model
parser = JsonOutputParser(
    name="user_review_evaluation",
    pydantic_object=ReviewEvaluation
)

# Get the format instructions generated by the parser
format_instructions = parser.get_format_instructions()

# Template that provides the review context
context_template = PromptTemplate.from_template(
    "You are evaluating customer reviews about a product. "
    "Extract the requested information from this review: {review}. "
)

# Template that defines the response language
language_template = PromptTemplate.from_template(
    "Always answer in {language}. ",
    partial_variables={
        "language": "English"
    }
)

# Template that defines the expected output format
format_template = PromptTemplate.from_template(
    "Response format: {format_instructions}. ",
    partial_variables={
        "format_instructions": format_instructions
    }
)

# Combine all templates into one final prompt
final_template = (
    context_template
    + language_template
    + format_template
)

# Create a LangChain chat model connected to OpenAI
model = ChatOpenAI()

# Process each review
for review in reviews:
    # Fill the prompt with the current review
    prompt = final_template.invoke(
        {
            "review": review
        }
    )

    # Send the prompt to the model
    response = model.invoke(prompt)

    # Parse the response into a structured JSON-like Python object
    parsed_response = parser.invoke(response)

    # Display the structured result
    print(parsed_response)