from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

# Load environment variables from the .env file
load_dotenv()

# Define the initial message that controls the assistant behavior
messages = [
    SystemMessage(
        content=(
            "Answer the questions in a short way, but not too short. "
            "Use a maximum of 140 characters."
        )
    )
]

# Create a LangChain chat model connected to OpenAI
model = ChatOpenAI()

# Ask the user to type a message in the terminal
user_message = input("Type your message: ")

# Add the user message to the conversation
messages.append(HumanMessage(content=user_message))

# Send the messages to the model and get a response
response = model.invoke(messages)

# Display the full response object
print(response)

# Display the response object type
print(type(response))

# Display only the text content generated by the model
print(response.content)

# Display the message type, usually "ai"
print(response.type)